//
//  NumberViewModel.swift
//  DeutschEdu
//
//  Created by Ella Huskovic on 24/11/2020.
//  Copyright © 2020 Ella Huskovic. All rights reserved.
//

import Foundation

class NumberViewModel: ObservableObject {
    @Published private(set) var numbers = [
        Number(imageName: "zero", base: "null", connector: "", sufix: ""),
        Number(imageName: "one", base: "ein", connector: "s", sufix: ""),
        Number(imageName: "two", base: "zwei", connector: "", sufix: ""),
        Number(imageName: "three", base: "drei", connector: "", sufix: ""),
        Number(imageName: "four", base: "vier", connector: "", sufix: ""),
        Number(imageName: "five", base: "fünf", connector: "", sufix: ""),
        Number(imageName: "six", base: "sech", connector: "s", sufix: ""),
        Number(imageName: "seven", base: "sieb", connector: "en", sufix: ""),
        Number(imageName: "eight", base: "acht", connector: "", sufix: ""),
        Number(imageName: "nine", base: "neun", connector: "", sufix: ""),
        Number(imageName: "ten", base: "zehn", connector: "", sufix: ""),
        Number(imageName: "eleven", base: "elf", connector: "", sufix: ""),
        Number(imageName: "twelve", base: "zwölf", connector: "", sufix: ""),
        Number(imageName: "thirteen", base: "drei", connector: "", sufix: "zehn"),
        Number(imageName: "fourteen", base: "vier", connector: "", sufix: "zehn"),
        Number(imageName: "fifteen", base: "fünf", connector: "", sufix: "zehn"),
        Number(imageName: "sixteen", base: "sech", connector: "", sufix: "zehn"),
        Number(imageName: "seventeen", base: "sieb", connector: "", sufix: "zehn"),
        Number(imageName: "eighteen", base: "acht", connector: "", sufix: "zehn"),
        Number(imageName: "nineteen", base: "neun", connector: "", sufix: "zehn"),
        Number(imageName: "twenty", base: "zwanzig", connector: "", sufix: ""),
        Number(imageName: "twentyone", base: "ein", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentytwo", base: "zwei", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentythree", base: "drei", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentyfour", base: "vier", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentyfive", base: "fünf", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentysix", base: "sechs", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentyseven", base: "sieben", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentyeight", base: "acht", connector: "und", sufix: "zwanzig"),
        Number(imageName: "twentynine", base: "neun", connector: "und", sufix: "zwanzig"),
        Number(imageName: "thirty", base: "dreißig", connector: "", sufix: ""),
        Number(imageName: "thirtyone", base: "ein", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtytwo", base: "zwei", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtythree", base: "drei", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtyfour", base: "vier", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtyfive", base: "fünf", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtysix", base: "sechs", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtyseven", base: "sieben", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtyeight", base: "acht", connector: "und", sufix: "dreißig"),
        Number(imageName: "thirtynine", base: "neun", connector: "und", sufix: "dreißig"),
        Number(imageName: "forty", base: "vierzig", connector: "", sufix: ""),
        Number(imageName: "fortyone", base: "ein", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortytwo", base: "zwei", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortythree", base: "drei", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortyfour", base: "vier", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortyfive", base: "fünf", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortysix", base: "sechs", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortyseven", base: "sieben", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortyeight", base: "acht", connector: "und", sufix: "vierzig"),
        Number(imageName: "fortynine", base: "neun", connector: "und", sufix: "vierzig"),
        Number(imageName: "fifty", base: "fünfzig", connector: "", sufix: ""),
        Number(imageName: "fiftyone", base: "ein", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftytwo", base: "zwei", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftythree", base: "drei", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftyfour", base: "vier", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftyfive", base: "fünf", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftysix", base: "sechs", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftyseven", base: "sieben", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftyeight", base: "acht", connector: "und", sufix: "fünfzig"),
        Number(imageName: "fiftynine", base: "neun", connector: "und", sufix: "fünfzig"),
        Number(imageName: "sixty", base: "sechzig", connector: "", sufix: ""),
        Number(imageName: "sixtyone", base: "ein", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtytwo", base: "zwei", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtythree", base: "drei", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtyfour", base: "vier", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtyfive", base: "fünf", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtysix", base: "sechs", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtyseven", base: "sieben", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtyeight", base: "acht", connector: "und", sufix: "sechzig"),
        Number(imageName: "sixtynine", base: "neun", connector: "und", sufix: "sechzig"),
        Number(imageName: "seventy", base: "siebzig", connector: "", sufix: ""),
        Number(imageName: "seventyone", base: "ein", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventytwo", base: "zwei", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventythree", base: "drei", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventyfour", base: "vier", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventyfive", base: "fünf", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventysix", base: "sechs", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventyseven", base: "sieben", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventyeight", base: "acht", connector: "und", sufix: "siebzig"),
        Number(imageName: "seventynine", base: "neun", connector: "und", sufix: "siebzig"),
        Number(imageName: "eighty", base: "achtzig", connector: "", sufix: ""),
        Number(imageName: "eightyone", base: "ein", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightytwo", base: "zwei", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightythree", base: "drei", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightyfour", base: "vier", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightyfive", base: "fünf", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightysix", base: "sechs", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightyseven", base: "sieben", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightyeight", base: "acht", connector: "und", sufix: "achtzig"),
        Number(imageName: "eightynine", base: "neun", connector: "und", sufix: "achtzig"),
        Number(imageName: "ninety", base: "neunzig", connector: "", sufix: ""),
        Number(imageName: "ninetyone", base: "ein", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetytwo", base: "zwei", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetythree", base: "drei", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetyfour", base: "vier", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetyfive", base: "fünf", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetysix", base: "sechs", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetyseven", base: "sieben", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetyeight", base: "acht", connector: "und", sufix: "neunzig"),
        Number(imageName: "ninetynine", base: "neun", connector: "und", sufix: "neunzig"),
        Number(imageName: "hunderd", base: "hundert", connector: "", sufix: ""),
        Number(imageName: "thousand", base: "tausent", connector: "", sufix: "")
    ]
}

